PREP(bootstrap);
PREP(extCallback);
PREP(onBootstrapReturn);
PREP(onClientConnected);
PREP(onPlayerConnected);
PREP(onPlayerDisconnected);
PREP(playerConnect);
PREP(playerDisconnect);
PREP(runAfterDatabaseInit);
