#define BLOODLESS_BLEEDING_COEF 0.75
#define BLOODLESS_PAIN_COEF 1.1
#define BLOODLESS_PAIN_KNOCKOUT_INCREASE 0.1
#define BREACHER_STAMINA_COEF 0.5
#define BURDEN_TO_BEAR_WEIGHT_COEF 0.5
#define COUNTERWEIGHT_RECOIL_COEF 0.8
#define COUNTERWEIGHT_PRIMARY_WEIGHT_INCREASE 0.1 // 0.1 -> increase by 10%
#define EOD_RANGE_COEF 1.5
#define HUNKERDOWN_BONUS_ARMOR_LEVEL 1
#define HUNKERDOWN_STAMINA_COEF 1.05
#define LOWDRAG_ARMOR_PENALTY 1
#define LOWDRAG_STAMINA_COEF 0.95
#define LOWDRAG_MUSCLE_DAMAGE_COEF 0
#define LUCKY_PROC_CHANCE 0.05
#define LUCKY_GRACE_PERIOD 2 // seconds
#define MARKSMAN_MINIMUM_SCOPE_MAGNIFICATION 4
#define OPERATOR_WEAPON_WEIGHT_COEF 0
#define OPERATOR_WEAPON_WEIGHT_CAP 50 // in arma "mass" units, 50 = 5lbs
#define PACKMULE_IGNORED_COEF 0.15
#define PHYSICIAN_EFFECTIVENESS COEF 1.33
#define RECON_MAX_ARMOR_LEVEL 3
#define RECON_VISIBILITY_COEF 0.6
#define RELENTLESS_PAIN_CAP 0 // 0-1, pain will be capped to this value upon waking up
#define ROCKANDSTONE_TIME_COEF 0.7
#define ROCKETMAN_WEIGHT_COEF 0.75
#define STYLE_OVER_SUBSTANCE_BONUS_ARMOR_LEVEL 2
#define SUPPRESSION_BONUS_COEF 1.5