name = "Skua Armory"
author = "LinkIsGrim"
prefix = "skua"
mainprefix = "z"

[files]
include = [
    "*.dll",
    "*.so",
    "mod.cpp",
    "meta.cpp",
    "logo_skua_armory_ca.paa",
    "README.md"
]

[version]
git_hash = 0
