name: Publish to Workshop

on:
  push:
    tags:
    - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Install Arma 3 Tools
      uses: arma-actions/arma3-tools@master
      with:
        toolsUrl: ${{ secrets.ARMA3_TOOLS_URL }}

    - name: Checkout the source code
      uses: actions/checkout@v1

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Cache cargo
      uses: Swatinem/rust-cache@v2

    - name: Install Windows build tooling
      run: |
        rustup target add x86_64-pc-windows-msvc
        cargo install cargo-xwin --locked

    - name: Install cross
      run: cargo install cross --locked

    - name: Set VERSION env
      run: echo VERSION=${GITHUB_REF:11} >> $GITHUB_ENV

    - name: Build Linux extension
      run: |
        cross build --release --locked --target x86_64-unknown-linux-gnu
        cp target/x86_64-unknown-linux-gnu/release/libskua.so skua_x64.so

    - name: Build Windows extension
      run: |
        cargo xwin build --release --target x86_64-pc-windows-msvc
        cp target/x86_64-pc-windows-msvc/release/skua.dll skua_x64.dll

    - name: Setup HEMTT
      uses: arma-actions/hemtt@v1
      with:
        annotate: false

    - name: Run HEMTT release
      run: hemtt release

    - name: Upload to Workshop
      uses: arma-actions/workshop-upload@v1
      with:
        appId: '107410'    # default
        itemId: '3680089530' # Id of item to update
        contentPath: '.hemttout/release'
        changelog: 'https://github.com/skua-international/skua-armory/releases/tag/v${{ env.VERSION }}' # set to github tag link
      env:
        STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
        STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
